name    'puppetlabs-havana'
version '0.0.1'
source 'Chris Hoge'
author 'puppetlabs'
license 'Apache License, Version 2.0'
summary 'Simplified OpenStack Havana Deployment with Puppet.'
description 'Using a hiera-based roles and profiles model, simplify OpenStack deployments.'
project_page 'https://github.com/puppetlabs/puppetlabs-havana'

## Add dependencies, if any:
dependency 'puppetlabs/openstack', '>=3.0.0 <4.0.0'
dependency 'puppetlabs/ntp', '>=2.0.0 <3.0.0'
dependency 'puppetlabs/firewall', '>=0.0.4 <1.0.0'
dependency 'puppetlabs/vswitch', '>=0.2.0 <1.0.0'
dependency 'puppetlabs/mongodb', '>=0.6.0 <1.0.0'
