name    'puppetlabs-havana'
version '3.0.0-rc5'
source 'Chris Hoge'
author 'Puppet Labs and Authors'
license 'Apache License, Version 2.0'
summary 'Simplified OpenStack Havana Deployment with Puppet.'
description 'Using a hiera-based roles and profiles model, do simple OpenStack deployments.'
project_page 'https://github.com/puppetlabs/puppetlabs-openstack'

## OpenStack Dependencies
dependency 'puppetlabs/keystone',    '>=3.1.1 <4.0.0'
dependency 'puppetlabs/swift',       '>=3.0.0 <4.0.0'
dependency 'puppetlabs/cinder',      '>=3.1.0 <4.0.0'
dependency 'puppetlabs/glance',      '>=3.1.0 <4.0.0'
dependency 'puppetlabs/neutron',     '>=3.2.0 <4.0.0'
dependency 'puppetlabs/nova',        '>=3.2.0 <4.0.0'
dependency 'puppetlabs/heat',        '>=3.1.0 <4.0.0'
dependency 'puppetlabs/ceilometer',  '>=3.1.1 <4.0.0'
dependency 'puppetlabs/horizon',     '>=3.1.0 <4.0.0'

# Other Dependencies
dependency 'puppetlabs/ntp',         '>=2.0.0 <3.0.0'
dependency 'puppetlabs/firewall',    '>=1.0.0 <2.0.0'
dependency 'puppetlabs/vswitch',     '>=0.2.0 <1.0.0'
dependency 'puppetlabs/mongodb',     '>=0.6.0 <1.0.0'
