# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.6.0"
VAGRANTFILE_API_VERSION = "2"

#Load Yaml libraries
require 'yaml'


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.define "puppet" do |puppet|
#    puppet.vm.box = "puppet"
    puppet.vm.network "private_network", ip: "192.168.11.3"
    puppet.vm.network "private_network", ip: "192.168.22.3"
    puppet.vm.network "private_network", ip: "172.16.33.3"
    puppet.vm.network "private_network", ip: "172.16.44.3"
    puppet.vm.hostname = "puppet"
    puppet.vm.provider :virtualbox do |vb|
      vb.name = "puppet"
      vb.memory = 512
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    end
    puppet.vm.synced_folder "../../", "/openstack"
  end

  config.vm.define "allinone" do |allinone|
#    allinone.vm.box = "allinone"
    allinone.vm.network "private_network", ip: "192.168.11.4"
    allinone.vm.network "private_network", ip: "192.168.22.4"
    allinone.vm.network "private_network", ip: "172.16.33.4"
    allinone.vm.network "private_network", ip: "172.16.44.4"
    allinone.vm.hostname = "allinone"
    allinone.vm.provider :virtualbox do |vb|
      vb.name = "allinone"
      vb.memory = 4092
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    end

    allinone.vm.provision "puppet" do |puppet|
      puppet.manifests_path = "provision_manifests"
      puppet.manifest_file = "base.pp"
    end

    allinone.vm.synced_folder "../../", "/openstack"
  end

end
